version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://localhost:8080
    networks:
      - spvending-manager_spring-network
networks:
  spvending-manager_spring-network:
    external: true